### ISSUE TITLE
Ubuntu 14.04 / sources.list / arch missing

### ISSUE THREAD

**Issue by rmoriz** [treasure-data/chef-td-agent#53] opened 2015-05-13 12:10 UTC
This cookbook by default creates the following entry in the /etc/apt/sources.list.d:

```
deb   http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib
```

Unfortunately this causes an error on ´apt-get update´

```
STDERR: W: Failed to fetch http://packages.treasuredata.com/2/ubuntu/trusty/dists/trusty/InRelease  Unable to find expected entry 'contrib/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
```

A possible fix is to create a sources.list with hardcoded architecture:

```
deb   [arch=amd64] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib
```

or with the apt cookbook LWRPs:

```ruby
   ...
  apt_repository "treasure-data" do
    uri source
    distribution dist
    arch 'amd64'   # this line new
    components ["contrib"]
    key "http://packages.treasuredata.com/GPG-KEY-td-agent"
    action :add
  end
   ...
```

**Comment by yyuu** [comment] 2015-05-13 12:36
td-agent doesn't provide i386 binary package for Ubuntu 14.04. Even if you can install with tweaking sources.list, td-agent won't work on Ubuntu 14.04 i386.

**Comment by rmoriz** [comment] 2015-05-13 12:53
vm is amd64, error still occurs.

**Comment by yyuu** [comment] 2015-05-13 13:21
Umm. I cannot reproduce such behaviour with Kitchen CI. It doesn't fail even on Ubuntu 14.04.

https://github.com/treasure-data/chef-td-agent/blob/58fc28e35437c2649d1dfacce2d91572d5709cd1/.kitchen.yml#L13

**Comment by rmoriz** [comment] 2015-05-13 13:27
Error occurs on a DigitalOcean vm (which afaik is kvm based), maybe Docker isn't showing this behaviour?

**Comment by rmoriz** [comment] 2015-05-13 18:22
One reason the CI does not fail could be:
https://github.com/opscode-cookbooks/apt/blob/master/providers/repository.rb#L191-Lundefined

"apt-get update" fails but manages to get the amd64 package list and is able to install td-agent.

```
* execute[apt-get update] action run[2015-05-13T18:19:03+00:00] ERROR: execute[apt-get update] (/tmp/kitchen/cookbooks/apt/providers/repository.rb line 156) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get update -o Dir::Etc::sourcelist='sources.list.d/treasure-data.list' -o Dir::Etc::sourceparts='-' -o APT::Get::List-Cleanup='0' ----
STDOUT: Get:1 http://packages.treasuredata.com trusty InRelease [1204 B]
Get:2 http://packages.treasuredata.com trusty/contrib amd64 Packages [387 B]

STDERR: W: Failed to fetch http://packages.treasuredata.com/2/ubuntu/trusty/dists/trusty/InRelease  Unable to find expected entry 'contrib/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
---- End output of apt-get update -o Dir::Etc::sourcelist='sources.list.d/treasure-data.list' -o Dir::Etc::sourceparts='-' -o APT::Get::List-Cleanup='0' ----
Ran apt-get update -o Dir::Etc::sourcelist='sources.list.d/treasure-data.list' -o Dir::Etc::sourceparts='-' -o APT::Get::List-Cleanup='0' returned 100; ignore_failure is set, continuing


================================================================================
Error executing action `run` on resource 'execute[apt-get update]'
================================================================================

```


However it's still broken, other resources who don't accept failures will crash the chef run.

**Comment by rmoriz** [comment] 2015-06-03 01:12
Looks like this happens when i386 as foreign-architecture is set via dpkg, e.g. in `/var/lib/dpkg/arch` or within `/etc/dpkg/dpkg.cfg.d/`. By design and https://wiki.debian.org/Multiarch/HOWTO it's required that all sources either have all archs or use the vendor field to limit the archs to the available, e.g. amd64 in your case.

Since the Docker images of Ubuntu are based on the Ubuntu Cloud Image, this may be the reason because packer-based VMs and provider images (e.g. DigitalOcean) seem to have i386 listed.

**Comment by jperville** [comment] 2015-09-02 13:42
I just submitted a simple PR for this issue. Thanks @rmoriz for explaining and suggesting the fix.

**Comment by jperville** [comment] 2015-09-03 14:46
I think we can close this issue now that the PR has been merged.

**Comment by yyuu** [comment] 2015-09-03 14:47
Thanks for your help!

**Closed by yyuu** 2015-09-03 14:47 UTC

**Comment by mgoldsborough** [comment] 2015-10-29 18:38
@yyuu any idea when this would be released on the marketplace?

**Comment by yyuu** [comment] 2015-10-29 21:03
Umm. Sorry for delay.... I confirmed yesterday that all tests are passing on latest master. I will release new version possibly today.

**Comment by yyuu** [comment] 2015-10-30 00:33
@mgoldsborough Released v2.1.2

https://supermarket.chef.io/cookbooks/td-agent/versions/2.1.2

**Comment by mgoldsborough** [comment] 2015-10-30 00:51
Thanks for the quick turn, @yyuu!

**Comment by jperville** [comment] 2015-10-30 08:07
Thank you @yyuu
